import type { NextPage } from 'next'
import Head from 'next/head'
//import Image from 'next/image'
//import styles from '../styles/Home.module.css'
import Form from 'react-bootstrap/Form'
import Button from 'react-bootstrap/Button'
import 'bootstrap/dist/css/bootstrap.min.css';
import { FormEventHandler, useRef } from 'react';



const Home: NextPage = () => {
    const username = useRef("");
    const password = useRef("");

    const login: FormEventHandler<HTMLFormElement> = async (e) => {
        e.preventDefault();


    }

  return (
    <div className="w-screen h-screen flex justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div style={{maxWidth:"300px", border: "3px solid gray", padding:"20px", borderRadius: "5px"}}> 
    <Form onSubmit={login}>
        <Form.Group className="mb-3" controlId="formBasicEmail">
            <Form.Label>Username</Form.Label>
            <Form.Control type="text" placeholder="Username" onChange={(e)=>{username.current = e.target.value}}/>
        </Form.Group>
        <Form.Group className="mb-3" controlId="formBasicPassword">
            <Form.Label>Password</Form.Label>
            <Form.Control type="password" placeholder="Password" onChange={(e)=>{password.current = e.target.value}}/>
        </Form.Group>
        <div className="d-grid gap-2">
            <Button variant="primary" type='submit' size="lg">
                Login
            </Button>
        </div>
    </Form>

    </div>


    </div>
  )
}

export default Home
